function getURLParameter(e){return decodeURI((RegExp(e+"=(.+?)(&|$)").exec(location.search)||[,null])[1])}function breakingBadfy(e,t){$(".twitter-share-button").attr("data-text","Breaking Bad-fy Me! nihas.net/BreakingBadfyMe?firstName="+e+"&lastName="+t),$(".fb-share-button").attr("data-href","http://nihas.net/BreakingBadfyMe?firstName="+e+"&lastName="+t),document.title=e+" "+t
var a=($.getJSON("https://smart-ip.net/geoip-json?callback=?",function(a){$.ajax({url:"https://script.google.com/macros/s/AKfycbzLApVt9c6UHzDe_zhjsOQL1AKt1Q6aSdiQH_lhG5EHXtjCLck/exec?firstName="+e+"&lastName="+t+"&host="+a.host+"&lang="+a.lang+"&countryName="+a.countryName+"&countryCode="+a.countryCode+"&city="+a.city+"&region="+a.region+"&latitude="+a.latitude+"&longitude="+a.longitude+"&timezone="+a.timezone+"&button=0"})}),findElement(e)),i=findElement(t)
console.log("---NEW NAME---"),console.log(a),console.log(i),a||(a=[{symbol:e.substr(0,1).toUpperCase()+e.substr(1,1).toLowerCase(),atomic_number:119,atomic_weight:256.0001,oxidation_states:"-",electronic_configuration:"[Zwg]5f¹6d¹7s²"},0,e+" (non element)"]),i||(i=[{symbol:t.substr(0,1).toUpperCase()+t.substr(1,1).toLowerCase(),atomic_number:119,atomic_weight:256.0001,oxidation_states:"-",electronic_configuration:"[Zwg]5f¹6d¹7s²"},0,t+" (non element)"])
var o=a[0],s=i[0],l=a[1],n=i[1]
$("#elementsName").html("You got "+a[2]+" and "+i[2]+"."),$("#bb-body").attr("style",""),$("#bb-name").html(""),$("<span class='title-1'><div class='chemical-element-out title-pre'>"+e.substr(0,l)+"</div></span><span class='chemical-element'>"+o.symbol+"<div class='desc' role='top-left'>"+o.atomic_weight+"</div><div class='desc' role='top-right'>"+oxidationStates(o)+"</div><div class='desc big' role='bottom-left-1'>"+o.atomic_number+"</div><div class='desc' role='bottom-left-2'>"+o.electronic_configuration+"</div></span><span class='title-1'><div class='chemical-element-out'>"+e.substr(l+o.symbol.length)+"</div></span><br><span class='title-1'></span><span class='title-1'><div class='chemical-element-out title-pre'>"+t.substr(0,n)+"</div></span><span class='chemical-element'>"+s.symbol+"<div class='desc' role='top-left'>"+s.atomic_weight+"</div><div class='desc' role='top-right'>"+oxidationStates(s)+"</div><div class='desc medium' role='bottom-left-1'>"+s.atomic_number+"</div><div class='desc' role='bottom-left-2'>"+s.electronic_configuration+"</div></span><span class='title-2'><div class='chemical-element-out'>"+t.substr(n+s.symbol.length)+"</div></span>").appendTo($("#bb-name")),(-1!=o.symbol.toLowerCase().indexOf("m")||-1!=s.symbol.toLowerCase().indexOf("m"))&&$(".chemical-element").css("padding","25px 0px 25px 0px"),audio.play(),navigator.userAgent.toLowerCase().indexOf("firefox")>-1&&(console.log("firefox"),$(".chemical-element").attr("style","width: 110px; height: 110px;"))}function oxidationStates(e){var t=e.oxidation_states
if("string"==typeof t){for(var a=t.split(","),i="",o=0;o<a.length;o++){var s=a[o].trim()
i+=(s>=0?"+":"")+s+"\n"}return i}return"number"==typeof t?(t>=0?"+":"")+t:void 0}function findElement(e){var t
for(var a in periodicTable)if(e.substr(0,2).toUpperCase()==periodicTable[a].symbol.toUpperCase())return[periodicTable[a],0,a]
for(t=0;t<e.length;t++)for(var a in periodicTable){var i=periodicTable[a].symbol
if(e.substr(t,i.length).toUpperCase()==i.toUpperCase())return[periodicTable[a],t,a]}return!1}$("#input-generate").click(function(){var e=$("#input-first-name").val(),t=$("#input-last-name").val()
location.search="?firstName="+e+"&lastName="+t}),$("#input-collapse").click(function(){"Close"==$("#input-collapse").html()?($("#input-group-collapsible").attr("style","height: 0px"),$("#input-collapse").html("Open")):($("#input-group-collapsible").attr("style","height: 200px"),$("#input-collapse").html("Close"))}),$(document).ready(function(){console.log("onload")
var e=getURLParameter("firstName"),t=getURLParameter("lastName")
"null"!==e&&"null"!==t&&($("#input-first-name").val(e),$("#input-last-name").val(t),breakingBadfy(e,t))})
